### ISSUE TITLE
Маленькие картинки на главной

### ISSUE THREAD

**Issue by TorinAsakura** [AtlantisUnited/plumsail#1]
Раздел Automate your business processes очень плохого качества, если открывать с телефона. 
Имеет смысл их сделать в бОльшем размере и уменьшить в CSS

**Comment by TorinAsakura** [comment]
Картинки и так в максимальном размере, либо давай нормальный растр либо я закрываю задачу, тут нечего делать
![monosnap 2017-10-02 22-30-58](https://user-images.githubusercontent.com/3940885/31079887-1502ede8-a7c2-11e7-9c4f-39065c756187.png)

**Comment by jusper-dk** [comment]
Нужен взять только таблицу:

**Comment by TorinAsakura** [comment]
@jusper-dk там все размеры номинальные, посмотри сам

**Comment by jusper-dk** [comment]
![wfpack](https://user-images.githubusercontent.com/27721442/31120486-3d8393a0-a83d-11e7-83b8-802591bb641e.png)

**Comment by alexsimkovich** [comment]
@jusper-dk что здесь делаем?

**Comment by jusper-dk** [comment]
На главной, в разделе Automate your business processes, первые две картинки мелкие - с телефона качество очень плохое. Поэтому меняем их на более крупные. Первая - картинка из вложения (см. выше) - чтобы выдержать пропорции надо просто добавить пространства сверху и снизу. Вторую надо вырезать отсюда:

**Comment by alexsimkovich** [comment]
@jusper-dk Проверяй

**Comment by jusper-dk** [comment]
Норм, только эта шапка не нужна, давай без нее. Просто блок-схема по центру 
![image](https://user-images.githubusercontent.com/27721442/32392949-b742d8fe-c0e8-11e7-84f1-e1ae14826a52.png)

**Comment by alexsimkovich** [comment]
@jusper-dk убрал и заменил
