### ISSUE TITLE
Ghost Button

### ISSUE THREAD

**Issue by TorinAsakura** [AtlantisUnited/plumsail#10]
Вместо этого ада запиленное на генераторе "CSS для школьников" (давно такого дерьма не видал оО)
```
border-top-width: 2px;
border-right-width: 2px;
border-bottom-width: 2px;
border-left-width: 2px;
border-top-style: solid;
border-right-style: solid;
border-bottom-style: solid;
border-left-style: solid;
border-top-color: rgb(142, 68, 172);
border-right-color: rgb(142, 68, 172);
border-bottom-color: rgb(142, 68, 172);
border-left-color: rgb(142, 68, 172);
border-image-source: initial;
border-image-slice: initial;
border-image-width: initial;
border-image-outset: initial;
border-image-repeat: initial;
background-image: initial;
background-position-x: 0px;
background-position-y: 0px;
background-size: initial;
background-repeat-x: initial;
background-repeat-y: initial;
background-attachment: initial;
background-origin: initial;
background-color: initial;
color: rgb(142, 68, 172);
font-size: 16px;
padding-top: 10px;
padding-right: 22px;
padding-bottom: 10px;
padding-left: 22px;
border-top-left-radius: 6px;
border-top-right-radius: 6px;
border-bottom-right-radius: 6px;
border-bottom-left-radius: 6px;
-webkit-background-clip: padding-box;
background-clip: padding-box;
transition-duration: 0.3s;
transition-timing-function: initial;
transition-delay: initial;
transition-property: initial;
```

Запилить нормальный Ghost Button с классификаторами по локации объекта

**Comment by alexsimkovich** [comment]
@jusper-dk подскажи, что здесь нужно сделать?

**Comment by TorinAsakura** [comment]
@alexsimkovich Просто компонент button, туда все кнопки по стайлгайду

**Comment by alexsimkovich** [comment]
@TorinAsakura @jusper-dk 
`.button
  display: inline-block
  min-width: 180px
  padding: 9px 31px
  margin-top: 21px
  font-size: 1rem
  font-weight: 400
  text-align: center
  color: $global-background
  background-color: transparent
  border-radius: 6px
  border: 2px solid transparent
  outline: none
  &[disabled]
    color: lighten($muted-color, 20%)
    border-color: lighten($muted-color, 40%)
    background-color: $node-color
    cursor: not-allowed
    &:hover,
    &:focus
      color: lighten($muted-color, 20%)
      border-color: lighten($muted-color, 40%)
      background-color: $node-color
      cursor: not-allowed
  &-primary
    border-color: $default-color
    background-color: $default-color
    &:hover,
    &:focus
      outline: none
      background-color: darken($default-color, 5%)
      border-color: darken($default-color, 5%)
  &-secondary
    border-color: $second-color
    background-color: $second-color
    &:hover,
    &:focus
      outline: none
      background-color: darken($second-color, 5%)
      border-color: darken($second-color, 5%)
  &-ghost-primary
    color: $default-color
    border-color: $default-color
    &:hover,
    &:focus
      color: $global-background
      outline: none
      background-color: darken($default-color, 5%)
      border-color: darken($default-color, 5%)
  &-ghost-secondary
    color: $second-color
    border-color: $second-color
    &:hover,
    &:focus
      color: $global-background
      outline: none
      background-color: darken($default-color, 5%)
      border-color: darken($default-color, 5%)
`
Пример кнопок:
`
<button type="button" class="button button-primary">Go to the dashboard</button>
<button type="button" class="button button-secondary">Go to the dashboard</button>
<button type="button" class="button button-ghost-primary">Go to the dashboard</button>
<button type="button" class="button button-ghost-secondary">Go to the dashboard</button>
<button type="button" class="button button-ghost-secondary" disabled="disabled">Go to the dashboard</button>
`

**Comment by jusper-dk** [comment]
На главной? 
Ghost secondary должен заполняться оранжевым при наведении - сейчас становится фиолетовой
![image](https://user-images.githubusercontent.com/27721442/32377248-0cae3e04-c0b8-11e7-85a5-c89b9bce15c5.png)

Обрати внимание, что в контексте продуктов у этих кнопой другие цвета (цвета продукта). Пример:
https://cyberthrone.org/sharepoint-dashboard-designer/
![image](https://user-images.githubusercontent.com/27721442/32377055-94608826-c0b7-11e7-8dfb-edd44152217e.png)

Это как должны выглядеть primary и ghost-primary внутри Dashboard Designer и для всех вложенных

**Comment by alexsimkovich** [comment]
@jusper-dk поправлено + описаны и пронаследованы стили для всех продуктов

**Comment by jusper-dk** [comment]
Добавь страничку style guide с базовыми элементами и примерами использования. Это в дальнейшем будет полезно, а сейчас кнопки смогу затестить.

**Comment by TorinAsakura** [comment]
@jusper-dk Это делай в статике Саня, просто хтмл страничку

**Comment by alexsimkovich** [comment]
@jusper-dk @TorinAsakura  разве не будет отдельно страницы стайлгайда по всем элементам?

**Comment by TorinAsakura** [comment]
@alexsimkovich Сейчас можно сделать статику, я потом её перенесу в wp_templates()

**Comment by jusper-dk** [comment]
Будет. Вот можешь как раз ее создать и добавить кнопки, чтобы можно было затестить.
