### ISSUE TITLE
Grid 1-3/1-1

### ISSUE THREAD

**Issue by TorinAsakura** [AtlantisUnited/plumsail#11]
[Original grid reference](https://plumsail.com/sharepoint-helpdesk/store/helpdesk-for-office-365/) Переписать [в этом разделе](http://cyberthrone.org/sharepoint-helpdesk/store/helpdesk-for-office-365/)

+ 500 comments - не отдельный тариф, а дополнение к любому из тарифов. Тарифов всего 3.

**Comment by jusper-dk** [comment]
https://cyberthrone.org/sharepoint-helpdesk/store/help-desk-for-office-365/
Разместить по центру, как на исходном сайте.

**Comment by TorinAsakura** [comment]
@jusper-dk это я и сам знаю, это к UI, закрываю
