### ISSUE TITLE
Link fixing

### ISSUE THREAD

**Issue by TorinAsakura** [AtlantisUnited/plumsail#12]
Пройтись по всем страницам с признаком •store• и дописать ссылки на avangate.com как это сделано на оригинальной версии

- [x] - https://cyberthrone.org/workflow-products-store/sp-2013-2016/ <--> https://plumsail.com
- [x] - https://cyberthrone.org/workflow-products-store/o365/ - licensing link
- [x] - https://cyberthrone.org/workflow-action-pack/support/ - follow us broken link

**Comment by jusper-dk** [comment]
Сравни
https://plumsail.com/workflow-products-store/o365/
https://cyberthrone.org/workflow-products-store/o365/

https://plumsail.com/workflow-products-store/sp-2013-2016/
https://cyberthrone.org/workflow-products-store/sp-2013-2016/

Дальше не смотрел. Но продукты должны совпадать, ссылки должны совпадать, иконки продуктов соответствовать.

**Comment by TorinAsakura** [comment]
@jusper-dk это уже UI, бизнесуха работает, закрываю
