### ISSUE TITLE
Минорные задачки

### ISSUE THREAD

**Issue by TorinAsakura** [AtlantisUnited/plumsail#13]
- [x] - Лого Workflow Scheduler for Office 365 должно быть такого же цвета, как у Workflow Actions Pack for Office 365 --> #EF6F42  
- [x] - Цвет логотипа Workflow Actions Pack 2013/2016 на странице http://cyberthrone.org/workflow-products-store/ --> #449f73
- [x] - Renewal так же лучше сделать таким же цветом
- [x] - Убрать заголовок Store и Automate your business processes  
- [x]   - http://cyberthrone.org/sharepoint-dashboard-designer/store/
- [x]   - http://cyberthrone.org/sharepoint-orgchart/store/
- [x]   - http://cyberthrone.org/sharepoint-helpdesk/store/
- [x]   - http://cyberthrone.org/workflow-products-store/
- [x] - [Forms designer](http://cyberthrone.org/store/) -> Forms
- [x] - https://plumsail.com/partners-and-resellers/ GET Locatech
- [x] - http://take.ms/3z5Lj - typo
- [x] - Проверить target внутренних ссылок
- [x] - [Убить 600 минутную поддержку](http://cyberthrone.org/support-minutes)
- [x] - http://cyberthrone.org/sharepoint-workflow-scheduler/ - kill Flexible, Support, Free Upgrades with Icons
- [x] - http://cyberthrone.org/sharepoint-workflow-scheduler/ -> out store link change -> http://cyberthrone.org/workflow-products-store/

**Comment by TorinAsakura** [comment]
@jusper-dk  - Убрать заголовок Store и Automate your business processes
Везде вообще? Или в каких-то конкретных местах?

**Comment by TorinAsakura** [comment]
@jusper-dk по первому пункту

> Лого Workflow Scheduler for Office 365 должно быть такого же цвета, как у Workflow Actions Pack for Office 365 --> #EF6F42
ты точно уверен? они же будут одинаковым цветом

**Comment by jusper-dk** [comment]
Automate your business processees убрать из стора. Ориентируйся на plumsail.com. Отлепи товары от шапки:
https://cyberthrone.org/workflow-products-store/

Ссылки, кроме Actions, некорректные и ведут не на магазы:
https://cyberthrone.org/store/

Цвета да, одинаковые для Office 365

**Comment by TorinAsakura** [comment]
@jusper-dk это их вёрстка, что значит отлепи, так она у них устроена, можно сделать костыль, но тогда начнёт плыть мобильная версия, вчера проверял, я просто убрал заголовок…

**Comment by TorinAsakura** [comment]
@jusper-dk проверяй

**Comment by TorinAsakura** [comment]
@jusper-dk ?

**Comment by TorinAsakura** [comment]
@jusper-dk ?

**Comment by jusper-dk** [comment]
Ссылки по крайней мере в Orgchart на магаз все битые, лого bundle Actions Pack + Scheduler, Automate Your Business Processes - по-прежнему на некоторых страницах. Просто посмотри как было: 
https://plumsail.com/store/

Перенси аккуратно ссылки, названия, цены, иконки соответствующие поставь.
