### ISSUE TITLE
Проверить и пофиксить вёрстку в адаптивном режиме <640px

### ISSUE THREAD

**Issue by TorinAsakura** [AtlantisUnited/plumsail#14]
[Проверить](http://cyberthrone.org/sharepoint-helpdesk/)
![sharepoint helpdesk - plumsail 2017-10-02 06-59-01](https://user-images.githubusercontent.com/3940885/31059566-56af4daa-a73f-11e7-9171-eb9e12809a1a.png)

**Comment by alexsimkovich** [comment]
@jusper-dk ready

**Comment by jusper-dk** [comment]
Норм, но иконки надо вернуть.

Было:
![image](https://user-images.githubusercontent.com/27721442/32312662-05af1730-bfb0-11e7-9e19-dba8d07130ca.png)

Стало:
![image](https://user-images.githubusercontent.com/27721442/32312675-0fdc50ce-bfb0-11e7-9cee-e71e1838103e.png)

Проверить также другие продукты. Иконки забрать отсюда:
http://test.asight.ru/sharepoint-helpdesk/

**Comment by alexsimkovich** [comment]
@jusper-dk Иконки вроде на месте. Проверь плз еще раз

**Comment by jusper-dk** [comment]
Картинок нет, кэш вычистил:
![image](https://user-images.githubusercontent.com/27721442/32362524-13326fa8-c07b-11e7-8c02-184a7f8d1a82.png)

**Comment by alexsimkovich** [comment]
@jusper-dk ок, нашел в чем проблема. Вроде пофиксид

**Comment by jusper-dk** [comment]
Совем мелких по-прежнему нет:
![image](https://user-images.githubusercontent.com/27721442/32373095-9aa96cf2-c0a8-11e7-960d-1b2c1e59e117.png)

**Comment by alexsimkovich** [comment]
@jusper-dk сейчас уже все на месте
