### ISSUE TITLE
Сверстать style guide template

### ISSUE THREAD

**Issue by TorinAsakura** [AtlantisUnited/plumsail#15]
Вероятно нужны UI элементы для фирм. стиля или типа того, не понятно, но, говорят надо сверстать, ок…

**Comment by TorinAsakura** [comment]
А где style guide?

**Comment by jusper-dk** [comment]
https://1drv.ms/i/s!AuLc4TTQhc8ekbltfE2ZWr4d6C9pvg

**Comment by jusper-dk** [comment]
Дополнение по style guide:
Следующие HTML-элементы должны быть в цветах продукта без добавления к-либо дополнительных классов: h1-h6, ul list, ol lists (bullets and numbers), a (link подчеркнутая, при наведении подчеркивание убирается), button (primary button by default).

Если страница находится вне контекста продукта, все эти элементы  должны быть фиолетовыми - базовый фирменный цвет.

Примеры, где это не так:
https://cyberthrone.org/sharepoint-orgchart/docs/version-history/

Мы в контексте Org Chart, поэтому заголовки должны быть голубыми, а у списка должен быть голубой bullet (квадратный). В левом меню при этом буллеты не нужны, там все остается как есть.

Второй пример:
https://cyberthrone.org/sharepoint-orgchart/support/
Здесь буллеты черные (должны быть голубыми). Поскольку это обычный контент, то и классов и списка быть не должно, он по умолчанию должен быть таким.

Третий пример:
https://cyberthrone.org/sharepoint-orgchart/docs/renewal-pricing/
тут наклыдваются какие-то левые стили, в результат secondary button оранжевая, цена фиолетовая - надо бы их убрать, чтобы использовались дефолтные secondary button в контексте продукта и заголовок h{x}
