### ISSUE TITLE
Org Chart Documentation anchors

### ISSUE THREAD

**Issue by TorinAsakura** [AtlantisUnited/plumsail#16]
[Проблемный раздел](http://test.asight.ru/sharepoint-orgchart/docs/templating-syntax/#if-block-helper)
[Reference](https://spform.com/documentation/apps-office-365-installation-guide#add-app)

Проверить похожие разделы и сравнить с оригиналом

**Comment by alexsimkovich** [comment]
@jusper-dk можешь описать что здесь нужно сделать/проверить?

**Comment by jusper-dk** [comment]
Это связано с левым меню - Андрей обещал сделать. На одну страницу ведет несколько пунктов меню с якорями, пример:
https://plumsail.com/sharepoint-orgchart/docs/templating-syntax/#example-of-template

Сейчас, как я понимаю, левым меню управлять вообще нельзя - это основная проблема.

**Comment by TorinAsakura** [comment]
@jusper-dk Которую я решу...

**Comment by jusper-dk** [comment]
Будет круто, левыми менюшками всех продуктов хочется управлять из админки. Плюс нужна поддержка иерархии.

**Comment by TorinAsakura** [comment]
@jusper-dk Сделаем...
