### ISSUE TITLE
Инверсия логотипов партнёров

### ISSUE THREAD

**Issue by TorinAsakura** [AtlantisUnited/plumsail#17]
На главной есть логотипы партнёров, надо:
- +/target='_blank'/
- +stateInitial: grayScale
- +stateIsActive: addColors

**Comment by TorinAsakura** [comment]
@jusper-dk подтверди

**Comment by TorinAsakura** [comment]
@jusper-dk Done

**Comment by jusper-dk** [comment]
Confirmed
