### ISSUE TITLE
Org Chart Page

### ISSUE THREAD

**Issue by TorinAsakura** [AtlantisUnited/plumsail#18]
Смигрировать картинки в стэк сетке с оригинального сайта

**Comment by alexsimkovich** [comment]
@jusper-dk подскажи, что здесь нужно сделать?

**Comment by jusper-dk** [comment]
Нужно убрать двойные рамки у картинок. Пример: 
![image](https://user-images.githubusercontent.com/27721442/32373025-50b4112e-c0a8-11e7-8f45-a12b510df3e2.png)
 
Эта картинка должны быть как на исходном сайте в планшете 
![image](https://user-images.githubusercontent.com/27721442/32373035-59f496fa-c0a8-11e7-8c05-e08490147944.png)

**Comment by alexsimkovich** [comment]
@jusper-dk рамки находятся на самой картинке(нет стилей добавляющих рамки). Мне перевырезать картинки с PSD?

**Comment by alexsimkovich** [comment]
@jusper-dk не совсем понял "Эта картинка должны быть как на исходном сайте в планшете" - они одинаковые...

**Comment by jusper-dk** [comment]
В смысле ее нужно положить в планшет, а рамки кропнуть - на исходном сайте не было тенюшек, но были рамки. Теперь они не нужны. Брать из PSD не надо, возьми те, что есть и просто обрежь рамки.

**Comment by alexsimkovich** [comment]
@jusper-dk готово, проверяй
