### ISSUE TITLE
Support page's

### ISSUE THREAD

**Issue by TorinAsakura** [AtlantisUnited/plumsail#19]
![final comments pdf 2017-10-02 07-29-52](https://user-images.githubusercontent.com/3940885/31059875-877a0bd8-a743-11e7-9282-dd2d24ba4b1e.png)

**Comment by TorinAsakura** [comment]
@jusper-dk я не нашёл подобных виджетов/ссылок на тестовом стенде, то, что на plumsail.com я посмотрел, но, у них такого я не видел, по сему - будь добр передать код для виджета который живёт тут https://plumsail.com/support/#pl-widget{a61a2443-ca64-4448-999a-70d776f408d81}/

**Comment by jusper-dk** [comment]
код в странице. Вот он (просто достал из source страницы):
<div class="pl-hd-widget" data-config="YTYxYTI0NDMtY2E2NC00NDQ4LTk5OWEtNzBkNzc2ZjQwOGQ4QDE="> </div> <script src="https://static-hd.plumsail.com/widget/widget.js"></script>

**Comment by jusper-dk** [comment]
`<div class="pl-hd-widget" data-config="YTYxYTI0NDMtY2E2NC00NDQ4LTk5OWEtNzBkNzc2ZjQwOGQ4QDE="> </div> <script src="https://static-hd.plumsail.com/widget/widget.js"></script>`

**Comment by TorinAsakura** [comment]
@jusper-dk этот код и я видел, но, я хотел получить код из первоисточника, коль уж это ваш сайт и у вас есть доступ…

**Comment by jusper-dk** [comment]
Это и есть первоисточник. Исходники виджета  тебе не нужны.

Заголовок только поломался. И при переходе сюда
https://cyberthrone.org/support/

Перекидывает сюда
https://cyberthrone.org/cross-site-lookup-for-sharepoint-2013-and-sharepoint-online-in-office-365/support/

У каждого продукта своя страничка support. Плюс есть общая. Надо поправить ссылку на дискурс в соответствующую категорию (на каждый продукт своя категория) и сделать ссылку на общую страницу support, где лежит виджет
https://plumsail.com/support/#pl-widget{a61a2443-ca64-4448-999a-70d776f408d81}/

Все аналогично тому, как сделано на plumsail.com

**Comment by alexsimkovich** [comment]
@jusper-dk расскажи что здесь нужно сделать

**Comment by jusper-dk** [comment]
Суть: перенести контент всех страниц support с текущего сайта: https://plumsail.com

В каждом продукте есть страница support, там есть ссылка на форум. Нужно пробежаться по всем таким страницам и поправить ссылку так, чтобы она вела но соответствующую тему в discourse. Можно сравнить с текущим сайтом, например
https://plumsail.com/sharepoint-orgchart/support/
https://plumsail.com/workflow-actions-pack/support/
https://plumsail.com/workflow-scheduler/support/

Плюс есть общая страница support, на ней должен лежать виджет, как сейчас:
https://plumsail.com/support/

Ну и причесать: беда с иконками соц сетей
![image](https://user-images.githubusercontent.com/27721442/32392516-0a7983c6-c0e7-11e7-8c28-3c4e984e7d31.png)

Большой отступ от заголовка
![image](https://user-images.githubusercontent.com/27721442/32392527-1970a7ec-c0e7-11e7-84c4-fed20e6e76bf.png)

https://cyberthrone.org/sharepoint-helpdesk/support/

То же с другими страницами поддержки. Еще обращай внимание на урлы страниц - они должны совпадать с урлами на исходном сайте (https://plumsail.com).

**Comment by alexsimkovich** [comment]
@jusper-dk проверяй

**Comment by jusper-dk** [comment]
Ну и мелочь: в списке, отсту от буллета лучше ограничить 20px (касается всех страниц):
https://cyberthrone.org/workflow-action-pack/support/

![image](https://user-images.githubusercontent.com/27721442/32407386-0f6fbe92-c199-11e7-9440-c4c86289e27e.png)

**Comment by jusper-dk** [comment]
Тут часть ссылок не в цветах продукта
https://cyberthrone.org/sharepoint-dashboard-designer/support/

![image](https://user-images.githubusercontent.com/27721442/32407399-3af4e1c8-c199-11e7-980e-295636598b7a.png)

**Comment by alexsimkovich** [comment]
@jusper-dk сейчас вроде бы готово
