### ISSUE TITLE
Стилизация ссылок

### ISSUE THREAD

**Issue by TorinAsakura** [AtlantisUnited/plumsail#2]
[Ссылки должны отличаться от текста, например, цветом. ](http://cyberthrone.org/sharepoint-dashboard-designer/dashboard-designer-documentation/)

[Reference](http://cyberthrone.org/sharepoint-dashboard-designer/dashboard-designer-documentation/sharepoint-list/ 
)

**Comment by jusper-dk** [comment]
https://cyberthrone.org/sharepoint-orgchart/docs/
Пройтись по другим продуктам и страницам.

**Comment by TorinAsakura** [comment]
@jusper-dk Done

**Comment by jusper-dk** [comment]
При наведении цвет не должен становиться серым:
![image](https://user-images.githubusercontent.com/27721442/32266154-56662e0c-bef7-11e7-98f4-5bd385bb544c.png)

Можно как у кнопки, немного затемнять:
![image](https://user-images.githubusercontent.com/27721442/32266193-73c9bedc-bef7-11e7-9bfb-e3c7d4c06137.png)

Либо просто убирать подчеркивание. Оба варианта ОК, но везде должно быть одинаково, включая дефолтные фиолетовые ссылки вне контекста продукта на общих страницах.

**Comment by TorinAsakura** [comment]
@jusper-dk Done
