### ISSUE TITLE
Редирект на старый блог

### ISSUE THREAD

**Issue by TorinAsakura** [AtlantisUnited/plumsail#20]
Переписать ссылки с [анкоров-заглушек](http://cyberthrone.org/sharepoint-orgchart/docs/) на треды старого форума, в последствии будет настроена переадресация

**Comment by jusper-dk** [comment]
Почти все HowTos указывают на блог
https://plumsail.com/sharepoint-orgchart/docs/

Тут ссылки битые, и не только в HowTos:
https://cyberthrone.org/sharepoint-orgchart/docs/

**Comment by TorinAsakura** [comment]
@jusper-dk Как ты мог заметить, орг чарты я ещё не трогал, иначе бы отрапортовал коммитами

**Comment by TorinAsakura** [comment]
@jusper-dk #4 Done
