### ISSUE TITLE
Customization and Support

### ISSUE THREAD

**Issue by TorinAsakura** [AtlantisUnited/plumsail#21]
[Отсюда](https://plumsail.com/sharepoint-helpdesk/store/customizations-and-support/) ДОмигрировать [сюда](http://cyberthrone.org/sharepoint-helpdesk/helpdesk-store/customizations-and-support/)

**Comment by jusper-dk** [comment]
Ссылки ведут на plumsail.com, где сами страницы с описанием кастомизаций?

**Comment by TorinAsakura** [comment]
@jusper-dk ты про страницы внутренние ничего не писал, я тебе больше скажу, их и asight не было

**Comment by TorinAsakura** [comment]
@jusper-dk и ссылки ведут на avangate, как и на сайте вашем родном, о каких страницах идёт речь я вообще не понимаю

**Comment by TorinAsakura** [comment]
@TorinAsakura а, я понял о чём ты, но, об внутренних страницах ты ничего не писал, ты дал ссылку на страницу с услугами, я её допилил, всё

**Comment by jusper-dk** [comment]
Подними чуть-чуть конетент, какой-то конский отступ от хлебных крошек до заголовка:
https://cyberthrone.org/sharepoint-helpdesk/store/customizations-and-support/

Вот нормальный отступ
https://cyberthrone.org/sharepoint-orgchart/docs/
https://cyberthrone.org/sharepoint-dashboard-designer/dashboard-designer-documentation/

Последний тайл битый
https://cyberthrone.org/sharepoint-helpdesk/store/customizations-and-support/

**Comment by TorinAsakura** [comment]
@jusper-dk Я уже сказал, весь UI после бизнесухи...
Тайл проверю, может не залилось или кэш у тебя

**Comment by TorinAsakura** [comment]
@jusper-dk 
- тайл не битый, хз как ты смотрел http://take.ms/I78xB
- отступы вот вообще не трогал, приводить к единому формату буду тогда, когда начну заниматься UI (скоро)

**Comment by jusper-dk** [comment]
Да, сайчас норм. Я получал 404, кэш чистил. Может кэш в Wp? В общем тут норм.

**Comment by jusper-dk** [comment]
Форма запроса и лайки остаются
https://cyberthrone.org/sharepoint-helpdesk/request-customization/

**Comment by alexsimkovich** [comment]
@jusper-dk расскажи что здесь нужно сделать

**Comment by jusper-dk** [comment]
См исходный сайт: была функция голосования за кастомизации (правый нижний угол каждого тайла)
https://plumsail.com/sharepoint-helpdesk/store/customizations-and-support/

И внутри, рядом с заголовком:
https://plumsail.com/sharepoint-helpdesk/store/customizations-and-support/canned-responses/

Плюс форма запроса с передачей параметра в урле (айди кастомизации, с которой перешли на форму):
https://plumsail.com/sharepoint-helpdesk/store/customizations-and-support/request-customization/?customizationId=3

Автоматически выбирается соответствующая кастомизация в выпадающем списке.

**Comment by TorinAsakura** [comment]
@jusper-dk плагин WP Ulike качаешь, активируешь (вроде уже стоял…) добавляешь хук, делаешь блок потоковым-флексовым - профит

**Comment by jusper-dk** [comment]
Проснулся! Формочка еще

**Comment by TorinAsakura** [comment]
@jusper-dk Ща, нулевой апдейт накатится и сяду

**Comment by alexsimkovich** [comment]
@TorinAsakura я уже даже лайки в svg скачал)

**Comment by TorinAsakura** [comment]
@alexsimkovich Ахахаахах)) нет нужды)) это плагинами) зачем сделаю))

**Comment by alexsimkovich** [comment]
@TorinAsakura я в Вордпрессе не шарю (

**Comment by TorinAsakura** [comment]
@alexsimkovich Норм, щас всё сделаем

**Comment by jusper-dk** [comment]
Так это выглядит в админке
[customizations.txt](https://github.com/AtlantisUnited/plumsail/files/1442967/customizations.txt)

**Comment by TorinAsakura** [comment]
@jusper-dk дерьмово) Тогда давай доступ к админке) Надо посмотреть откуда шоткод растёт чтобы переповторить и ничего не просрать

**Comment by jusper-dk** [comment]
![image](https://user-images.githubusercontent.com/27721442/32403799-2d8b4f6c-c154-11e7-9618-9a31a48ea5ab.png)

**Comment by jusper-dk** [comment]
Сверстать голосование за фичи:
слева цена, справа голосовалка

Иконку оставить стандартную. Если проголосовал - делать оранжевой:
https://cyberthrone.org/wp-content/plugins/wp-ulike/assets/img/icons/add.png

То же внутри фичи
https://cyberthrone.org/sharepoint-helpdesk/store/customizations-and-support/canned-responses/

Также рядом в заголовком:
https://plumsail.com/sharepoint-helpdesk/store/customizations-and-support/canned-responses/

Обрати внимание, что цвета на страницах фич должны быть HelpDesk (контекст продукта).

**Comment by alexsimkovich** [comment]
@jusper-dk Ready

**Comment by jusper-dk** [comment]
Убрать декоративный элемент, который пришел с главной (на главной оставить) 
![image](https://user-images.githubusercontent.com/27721442/32449161-e62cb942-c321-11e7-81c3-93c56805f811.png)

Почему на этих страницах нет breadcrumbs?
https://cyberthrone.org/sharepoint-helpdesk/store/customizations-and-support/assign-to-me-button/

После лайка и обновления страницы палет, рука остается серой, но при этом некликабельной:
![image](https://user-images.githubusercontent.com/27721442/32449226-10d0e07e-c322-11e7-9036-29cfd3e10336.png)

Буллеты должны быть оранжевыми (это есть в другой таске, но можно сделать и сейчас)
![image](https://user-images.githubusercontent.com/27721442/32449259-24d87e4c-c322-11e7-88d5-2ad9e71f42a4.png)

**Comment by alexsimkovich** [comment]
@jusper-dk все поправил. Лайки у меня нормально работают

**Comment by jusper-dk** [comment]
60 support minutes - только нижняя часть ссылка. Надо, чтобы ссылкой был весь бокс, как в кастомизациях
https://cyberthrone.org/sharepoint-helpdesk/store/customizations-and-support/

Странный выпадающий список без стрелочки
![image](https://user-images.githubusercontent.com/27721442/32451055-f6974734-c326-11e7-8e14-f22abdd573dd.png)

**Comment by alexsimkovich** [comment]
@jusper-dk fixed
