### ISSUE TITLE
Главная: в меню потерялись пиктограммы соц. сетей

### ISSUE THREAD

**Issue by jusper-dk** [AtlantisUnited/plumsail#26]
![image](https://user-images.githubusercontent.com/27721442/32230171-9c1de9e2-be63-11e7-981d-673c1f66fc9e.png)

**Comment by alexsimkovich** [comment]
@jusper-dk done

**Comment by jusper-dk** [comment]
Пиксельная рамка внутри 
![image](https://user-images.githubusercontent.com/27721442/32281221-4119988a-bf2f-11e7-847c-fe7070fe8f1b.png)

**Comment by alexsimkovich** [comment]
@jusper-dk fixed
