### ISSUE TITLE
Главная: иконки 5000+ happy customers

### ISSUE THREAD

**Issue by jusper-dk** [AtlantisUnited/plumsail#28]
Не надо отводить им столько места в мобильной версии:
![image](https://user-images.githubusercontent.com/27721442/32230502-60798daa-be64-11e7-828c-7b57e7587118.png)

Лучше как раньше:
![image](https://user-images.githubusercontent.com/27721442/32230526-6ebcefb0-be64-11e7-93b7-5bb81fd5245a.png)

**Comment by alexsimkovich** [comment]
@jusper-dk done
