### ISSUE TITLE
Хьюстон! Мы потеряли вложенность!

### ISSUE THREAD

**Issue by TorinAsakura** [AtlantisUnited/plumsail#3]
Слева в меню теряется [уровень вложенности](http://cyberthrone.org/sharepoint-dashboard-designer/dashboard-designer-documentation/sharepoint-list/ ), все одним списком сложно воспринимать.

[Reference](https://spform.com/documentation/sp2013install)

[Reference2](http://cyberthrone.org/docs/help-desk-o365/v1.x/How%20To/Configure%20assigning%20based%20on%20forwarding%20address.html 
)

**Comment by TorinAsakura** [comment]
@jusper-dk потрудись пожалуйста пояснить где тут родитель, а где потомок, на SPForms.com к примеру всего 6 разделов против наших 15+ http://take.ms/LxPfZ

**Comment by alexsimkovich** [comment]
@TorinAsakura @jusper-dk что по этому таску?

**Comment by TorinAsakura** [comment]
@alexsimkovich это относилось к неуправляемым сайдбарам, теперь сайдбаром можно управлять как и его вложенностью, всё автоматизированно, только вёрстку причесать

**Comment by jusper-dk** [comment]
Активный пункт должен быть темнее (как primary button при наведении) и без подчеркивания

Расстояние от родительского пункта до дочернего такое же как между пунктами одного уровня:
![image](https://user-images.githubusercontent.com/27721442/32414135-5bfbdbe0-c231-11e7-8f18-5378f7ba5701.png)
здесь надо увеличить отступ от Configuration Wizard до How to ...

Что-то пошло не так с первым заголовком:
![image](https://user-images.githubusercontent.com/27721442/32414138-7b264f8c-c231-11e7-99c2-f0bee2620ae5.png)
https://cyberthrone.org/sharepoint-orgchart/docs/orgchart-installation-2010/

Установить наследование sidebar для всех страниц документации

Добавить sidebar в доки Dashboard Designer и Workflow Scheduler и также унаследовать для всех страниц и документации.
