### ISSUE TITLE
Главная: в мобильной версии убрать рамки у картинок и растянуть их на всю ширину

### ISSUE THREAD

**Issue by jusper-dk** [AtlantisUnited/plumsail#30]
Сайчас так:
![image](https://user-images.githubusercontent.com/27721442/32230894-33c13776-be65-11e7-978d-2a1dbd744777.png)

Надо так:
![image](https://user-images.githubusercontent.com/27721442/32230913-42f2a324-be65-11e7-8bea-d498d24e8ca4.png)

**Comment by alexsimkovich** [comment]
Done

**Comment by alexsimkovich** [comment]
@jusper-dk
