### ISSUE TITLE
Главная: шрифт главного меню сделать чуть жирнее, как раньше

### ISSUE THREAD

**Issue by jusper-dk** [AtlantisUnited/plumsail#32]
Было:
![image](https://user-images.githubusercontent.com/27721442/32267915-eeb55772-befd-11e7-84bf-ef70db80d8ff.png)

Стало:
![image](https://user-images.githubusercontent.com/27721442/32267927-fb604ae0-befd-11e7-9601-5ba63e1f779f.png)

**Comment by alexsimkovich** [comment]
Done

**Comment by jusper-dk** [comment]
Confirmed
