### ISSUE TITLE
Партнеры: Лого партнеров или весь блок должен вести на сайт партнера

### ISSUE THREAD

**Issue by jusper-dk** [AtlantisUnited/plumsail#33]
https://cyberthrone.org/partners-and-resellers/

ссылки взять отсюда:
https://plumsail.com/partners-and-resellers/

Убрать фиолетовый бэкграунд у патнеров, хз откуда он там взялся.

кроме этого один партнер не поместился в блок:
![image](https://user-images.githubusercontent.com/27721442/32287091-b7e8b69c-bf40-11e7-88cf-534f2f299685.png)

можно убрать последнее предложение: HelpDesk localization contributors.

**Comment by alexsimkovich** [comment]
@jusper-dk ready

**Comment by alexsimkovich** [comment]
@jusper-dk ready

**Comment by jusper-dk** [comment]
Давай либо только лого - ссылка, либо весь блок внутри рамки. Сейчас лого и текст, а между ними ссылки нет.

Кнопка Become a partner была в правильном месте под заголовкой Trusted partners, по центру.

Отступ от заголовка до логотипов уменьшить (30px достаточно).
![image](https://user-images.githubusercontent.com/27721442/32312526-52da7546-bfaf-11e7-905f-0ea4eb660d4f.png)

**Comment by alexsimkovich** [comment]
@jusper-dk fixed
