### ISSUE TITLE
Магазин: перенести магазин с plumsail.com

### ISSUE THREAD

**Issue by jusper-dk** [AtlantisUnited/plumsail#35]
**Org Chart**

Тут отсутствуют ссылки:
https://cyberthrone.org/sharepoint-orgchart/store/

Взять отсюда:
https://plumsail.com/sharepoint-orgchart/store/

Расположить в три колонки, как здесь:
https://cyberthrone.org/sharepoint-dashboard-designer/store/

Сделать порядок, как в оригинальном магазе
https://plumsail.com/sharepoint-orgchart/store/

Добавить отступ от шапки (30px)
![image](https://user-images.githubusercontent.com/27721442/32413410-fc4ae272-c221-11e7-818f-637cb493904e.png)

**Dashboard Designer**

Тут некоторые ссылки неправильные:
https://cyberthrone.org/sharepoint-dashboard-designer/store/

Сравнить с:
https://plumsail.com/sharepoint-dashboard-designer/store/

иконка 60 support minutes должна быть эта:
https://cyberthrone.org/support-minutes/

Добавить отступ от шапки (30px норм)
![image](https://user-images.githubusercontent.com/27721442/32413397-b708f50a-c221-11e7-8e44-252bbf3e8a3e.png)

**Workflows**

Отступ от шапки
![image](https://user-images.githubusercontent.com/27721442/32413437-580552be-c222-11e7-9e4d-b6be4a4733ee.png)

Убрать зоголовок отовсюду, где встречается в магазе:
https://cyberthrone.org/workflow-products-store/o365/
![image](https://user-images.githubusercontent.com/27721442/32413447-70c57bc6-c222-11e7-8c66-38e1f0460f4d.png)

Иконки, цены, названия должны совпадать:
https://cyberthrone.org/workflow-products-store/o365/

Исходный вариант:
https://plumsail.com/workflow-products-store/o365/

То же самое:
https://cyberthrone.org/workflow-products-store/sp-2013-2016/
https://plumsail.com/workflow-products-store/sp-2013-2016/

И здесь:
https://cyberthrone.org/workflow-products-store/workflow-scheduler-for-office-365/
https://plumsail.com/workflow-scheduler-store/o365/

Тут нет ссылок:
https://cyberthrone.org/workflow-products-store/workflow-sheduler-for-sharepoint/
https://plumsail.com/workflow-scheduler-store/sp-2013-2016/

Кнопки должны быть primary (цвета продукта, заполненные)

**HelpDesk**
https://cyberthrone.org/sharepoint-helpdesk/store/help-desk-for-office-365/

Убрать Automate Your Business Processes

Отступ от цены до кнопки, от кнопки до текста сократить, сделать одинаковым:
![image](https://user-images.githubusercontent.com/27721442/32413612-276339e2-c226-11e7-8606-2ad507b5b501.png)

Поместить в рамку все содержимое, относящееся к продукту
![image](https://user-images.githubusercontent.com/27721442/32413628-8c187b36-c226-11e7-8c98-4fd945a8b774.png)

Комментарии разместить по центру, текст Jet boat убрать
![image](https://user-images.githubusercontent.com/27721442/32413631-a327cbb0-c226-11e7-9b0b-a6230f947e1c.png)

Буллеты должны быть оранжевыми в контексте продукта

Проверить все ссылки, сравнив с оригиналом:
https://plumsail.com/sharepoint-helpdesk/store/

**Customizations**
https://cyberthrone.org/sharepoint-helpdesk/store/customizations-and-support/

Тут откуда-то взялся декоративный элемент с главной - убрать, но только отсюда - на главной оставить.

Внутри причесать отступы как везде и поскольку мы в контексте продукта здесь цвета должны быть оранжевыми:
![image](https://user-images.githubusercontent.com/27721442/32413664-9d5ab764-c227-11e7-8d39-171d3ef263bd.png)

https://cyberthrone.org/sharepoint-helpdesk/store/customizations-and-support/canned-responses/

То же с остальными кастомизациями

**Все урлы сделать консистентными:**
/product/store/sub-category

У workflows чуть сложенее, тк там объединяется два продукта (Workflow Actions Pack & Scheduler):
/workflows/store
/workflows/store/sp-2013-2016
/workflows/store/o365/
etc

**Comment by alexsimkovich** [comment]
@jusper-dk список недостяющих картинок

1. Bundle: Workflow Actions Pack and Workflow Scheduler - https://plumsail.com/workflow-products-store/o365/
2. Workflow Actions Pack Development License - https://plumsail.com/workflow-products-store/sp-2013-2016/
3. Bundle: Workflow Actions Pack and Workflow Scheduler - https://plumsail.com/workflow-scheduler-store/o365/

**Comment by alexsimkovich** [comment]
@jusper-dk все, кроме картинок поправлено в магазине. Проверяй

**Comment by jusper-dk** [comment]
Browser Edge:
![image](https://user-images.githubusercontent.com/27721442/32595765-2d2326b6-c542-11e7-824e-11e4a4dd48a8.png)

Кнопки при наведении убегать не должны
![image](https://user-images.githubusercontent.com/27721442/32595780-40292bac-c542-11e7-9d76-3331d4bd401a.png)

Раньше так было сделано, чтобы весь текст поместился, а сейчас он помещается и так, так что можно эту анимашку убрать вообще
http://new.plumsail.com/workflow-products-store/o365/

Прижать футер к нижней части экрана (но фиксированным не делать):
http://new.plumsail.com/store/

Кнопка открывает avangate в том же окне
![image](https://user-images.githubusercontent.com/27721442/32596125-44008be8-c543-11e7-8dde-1286b41ccb2f.png)

Что за М после 365
http://new.plumsail.com/sharepoint-orgchart/store/
![image](https://user-images.githubusercontent.com/27721442/32596402-3bd1bde2-c544-11e7-9072-11d3b86858b1.png)

Тут расположение должно быть как на старом сайте: в певой строке тарифы, на следующей в центре каменты
http://new.plumsail.com/sharepoint-helpdesk/store/helpdesk-for-office-365/

Магазин Workflows пусть будет потомком проукта Workflow Actions Pack, a URL - store:

Те адрес например этой страницы
http://new.plumsail.com/workflow-products-store/o365/

будет:
http://new.plumsail.com/workflow-action-pack/store/o365/

Этой 
http://new.plumsail.com/workflow-products-store/sp-2013-2016/

такой:
http://new.plumsail.com/workflow-action-pack/store/sp-2013-2016/

итд

Лого недостающих продуктов приаттачу сл. каментом.

**Comment by alexsimkovich** [comment]
@jusper-dk закроешь здесь этот таск если все ок, чтобы я его не переносил
