### ISSUE TITLE
Downloads: страницы со ссылками на скачивание

### ISSUE THREAD

**Issue by jusper-dk** [AtlantisUnited/plumsail#36]
Для некоторых продуктов не хватает страниц со ссылками на скачивание. Переход на эти страницы осуществляется после сабмита соответствующей формы. Проверить все продукты (кроме Forms Designer & Cross-site Lookup) и если страницы нет, добавить по аналогии с plumsail.com.

**Comment by alexsimkovich** [comment]
@jusper-dk ready to check

**Comment by jusper-dk** [comment]
Проверь плз, что формы скачивания ведут на правильные страницы после сабмита. Например Actions Pack не ведет сюда:
http://new.plumsail.com/workflow-action-pack/download-links/

**Comment by alexsimkovich** [comment]
@jusper-dk fixed
