### ISSUE TITLE
Reviews: фото, имена, и ссылки на профили пользователей

### ISSUE THREAD

**Issue by jusper-dk** [AtlantisUnited/plumsail#37]
Снизу вставлен виджет Yotpo с отзывами клиентов:
https://cyberthrone.org/sharepoint-helpdesk/
https://cyberthrone.org/workflow-action-pack/
https://cyberthrone.org/sharepoint-workflow-scheduler/
https://cyberthrone.org/sharepoint-orgchart/

См оригинальный сайт:
https://plumsail.com/workflow-actions-pack/#reviews

В отзывах (Reviews) на всех страницах продуктов должны отображаться фото клиентов и их реальные имена. Сейчас это сделано с помощью скрипта, который сопоставляет имя и фото по адресу эл. почты и подменяет html прямо на странице. Эту функциональность хочется сохранить и вынести в отдельный js-файл или админку WP, чтобы можно было легко добавлять данные для новых пользователей, оставивших отзыв.

**Comment by TorinAsakura** [comment]
@jusper-dk я уже говорил, это функционал виджета, выносить это в админку - боль и ад и не один десяток часов уйдёт

**Comment by jusper-dk** [comment]
Меня утсроит просто скрипт с массивом из данных. Можно json, без разницы. Обсудим с @alexsimkovich ближе к делу
