### ISSUE TITLE
Scheduler: поменять картинки на лэндинге

### ISSUE THREAD

**Issue by jusper-dk** [AtlantisUnited/plumsail#38]
https://cyberthrone.org/sharepoint-workflow-scheduler/
Картинки в низком качестве 

Нужно взять за основу эти, вырезать области, которые показываются сейчас и вставить бОльшего размера:
https://static.plumsail.com/wp-content/uploads/SchedulingInterfaceLarge.png 
https://static.plumsail.com/wp-content/uploads/SchedulerTasksListLarge.png

**Comment by alexsimkovich** [comment]
@jusper-dk повырезал, залил большого размера. Проверяй
