### ISSUE TITLE
Отсутствует target в ссылках

### ISSUE THREAD

**Issue by TorinAsakura** [AtlantisUnited/plumsail#4]
В меню с продуктами ссылки на другие домены должны открываться в новой вкладке. 
Например, Forms Designer -> Documentation

TODO: тупо пройтись по кросслинкам на внешние ресурсы и добавить к ним target="_blank", шуму больше чем работы…

**Comment by jusper-dk** [comment]
Ссылки внутри домена должны открываться в том же окне. Тут это не так
https://cyberthrone.org/sharepoint-orgchart/docs/

**Comment by TorinAsakura** [comment]
@jusper-dk Done

**Comment by jusper-dk** [comment]
Confirmed
