### ISSUE TITLE
HelpDesk: перенести Why Plumsail HelpDesk с оригинального сайта

### ISSUE THREAD

**Issue by jusper-dk** [AtlantisUnited/plumsail#40]
https://plumsail.com/sharepoint-helpdesk/why-plumsail-helpdesk/

**Comment by alexsimkovich** [comment]
@jusper-dk Ready. https://cyberthrone.org/sharepoint-helpdesk/why-plumsail-helpdesk/

**Comment by jusper-dk** [comment]
Ссылка на стор не работает
![image](https://user-images.githubusercontent.com/27721442/32449415-8e423396-c322-11e7-967b-f13c2963adcd.png)

https://cyberthrone.org/sharepoint-helpdesk/store/helpdesk-for-office-365/

В магазе надо поправить адрес страницы, тут URL правильный

**Comment by alexsimkovich** [comment]
@jusper-dk Done
