### ISSUE TITLE
Workflow Actions Pack: переверстать лэндинг

### ISSUE THREAD

**Issue by jusper-dk** [AtlantisUnited/plumsail#41]
Сейчас:
https://cyberthrone.org/workflow-action-pack/

Хочется все пункты расположить списком, а не тайлами. Пример:
![image](https://user-images.githubusercontent.com/27721442/32438447-9244cbce-c2fb-11e7-9818-ca5ab36559ce.png)

Иконку Scheduler (последний пункт) нужно сделать фиолетовой - primary color of Workflow Scheduler

**Comment by alexsimkovich** [comment]
@jusper-dk ready
