### ISSUE TITLE
Menu: сделать меню и sidebar для продуктов - Dashboard Designer, Workflow Scheduler, Org Chart

### ISSUE THREAD

**Issue by jusper-dk** [AtlantisUnited/plumsail#42]
1. Доделать меню для всех трех продуктов с возмоностью управления из WP админки.
2. Добавить сайдбар для всех трех продуктов, заполнить меню сайдбара.
3. При открытии страницы, раскрывать только ту ноду меню, в котором находится активная страница. Остальные по умолчанию должны быть схлопнуты
4. Добавить слева от ноды верхнего уровня "+" и меня на "-" при раскрытии.
5. Активный пункт должен быть темнее (как primary button при наведении) и без подчеркивания
6. Расстояние от родительского пункта до дочернего такое же как между пунктами одного уровня:
7. Поменять шаблон всех страниц на соответствующий шаблон содержащий сайдбар.

**Comment by jusper-dk** [comment]
+- должны быть основного цвета продукта:
![image](https://user-images.githubusercontent.com/27721442/32489991-af9ee7c8-c3c2-11e7-9485-18c412f5ffff.png)

Расстояние между нодами верхнего уровня уменьшить до 35px
![image](https://user-images.githubusercontent.com/27721442/32490011-caa7b6ee-c3c2-11e7-9829-82b9a049c52c.png)

Сделать одинаковый отступ по вертикали
![image](https://user-images.githubusercontent.com/27721442/32490024-d89b272c-c3c2-11e7-8d61-7d083ce6ab61.png)

На индексной тоже поправить отступы
![image](https://user-images.githubusercontent.com/27721442/32490043-e6bbd176-c3c2-11e7-9c7e-52c824e314ad.png)

Шаблоны страниц поменять
https://cyberthrone.org/sharepoint-orgchart/docs/advanced-web-part-configuration/

**Comment by TorinAsakura** [comment]
@jusper-dk Done

**Comment by jusper-dk** [comment]
Причесать отступ:
https://cyberthrone.org/sharepoint-orgchart/docs/
![image](https://user-images.githubusercontent.com/27721442/32539307-0eef88ec-c47a-11e7-9861-54b04ccdefbe.png)

![image](https://user-images.githubusercontent.com/27721442/32539323-1ce83926-c47a-11e7-8550-7f7908fdca1f.png)

При наведении подчеркивание не убирается
![image](https://user-images.githubusercontent.com/27721442/32539392-503690c0-c47a-11e7-9088-671a786c3dbd.png)

При наведении на активный пункт, подчеркивание не должно появляться.

Выровнять по середине первой строки:
Сейчас
![image](https://user-images.githubusercontent.com/27721442/32539606-0a82741c-c47b-11e7-942b-2d1ed0669992.png)

Должно быть:
![image](https://user-images.githubusercontent.com/27721442/32539680-4b08bd52-c47b-11e7-97ee-cba7fcc9c3ed.png)

Остальное ОК.

**Comment by jusper-dk** [comment]
Что-то пошло не так (orgchart, меню от DD):
https://cyberthrone.org/sharepoint-orgchart/docs/templating-syntax/#example-of-template
![image](https://user-images.githubusercontent.com/27721442/32541848-edde264c-c481-11e7-9d91-43068a96a75e.png)

https://cyberthrone.org/sharepoint-orgchart/docs/orgchart-installation-2010/
https://cyberthrone.org/sharepoint-orgchart/docs/orgchart-installation-office-365/

**Comment by jusper-dk** [comment]
Активный пункт при наведении не должен подчеркиваться - писал в предыдущем каменте.
![image](https://user-images.githubusercontent.com/27721442/32541971-4e7e67a0-c482-11e7-9f54-5926e0ce45e2.png)
