### ISSUE TITLE
Dashboard Designer Documentation -> Demo

### ISSUE THREAD

**Issue by TorinAsakura** [AtlantisUnited/plumsail#6]
[Сюда](http://cyberthrone.org/sharepoint-dashboard-designer/dashboard-designer-documentation/) перенести [это](http://www.spchart.com/demo)

**Comment by TorinAsakura** [comment]
Все графики/чарты и прочую анимационную хрень тупо заскриншотить? Серьёзно?!

**Comment by jusper-dk** [comment]
Да, анимации не надо. Присто скрин графика на выходе.

**Comment by TorinAsakura** [comment]
@jusper-dk будь другом, распиши конкретно, что перенести ибо там разделов родительских 4, а там ещё потомков тьма и в каждом потомке куча данных в скролл-слайд таблице, графики - понятно, скриншотами, а таблица с демо-данными? и прочие штуки?

**Comment by jusper-dk** [comment]
Таблицу с демо данными тоже заскринить и выложить картинкой

Сверху сохранить навигацию, как было раньше
![image](https://user-images.githubusercontent.com/27721442/32377402-95ec7f96-c0b8-11e7-8a76-3ba8fdf5784d.png)
http://www.spchart.com/demo/ceo-dashboard 

Можно на каждый пункт не создавать отдельной страницы, а сделать навигацию как по табам, но с хэшем в уроле, чтобы можно было кинуть ссылку только на конфигурацию, например.

Перенести надо все из этого меню:
![image](https://user-images.githubusercontent.com/27721442/32377494-e5a73aa8-c0b8-11e7-99f9-a5ab8e198f64.png)
http://www.spchart.com/demo

**Comment by alexsimkovich** [comment]
@jusper-dk добавил табы и скрипт к ним (файл custom.js)
