### ISSUE TITLE
mouseOver issue

### ISSUE THREAD

**Issue by TorinAsakura** [AtlantisUnited/plumsail#7]
[Вот тут](http://cyberthrone.org/sharepoint-helpdesk/) нужно добавить не много любви к коду
Что-то вроде того, я думаю, хз, сырсы ещё не смотрел…
```
$(".someDiv")
        .mouseover(function () { $(this).pauseAnimation(); })
        .mouseout(function () { $(this).resumeAnimation(); })
```

TODO: ещё добавить индексы объектов для синхронной подсветки при срабатывании mouseover

**Comment by TorinAsakura** [comment]
@jusper-dk Done

**Comment by jusper-dk** [comment]
При наведении соответствующий пункт не подствечивается
https://cyberthrone.org/sharepoint-helpdesk/

**Comment by jusper-dk** [comment]
Области подсветки сейчас неправильные. Должны быть:
![image](https://user-images.githubusercontent.com/27721442/32278112-a92af05e-bf25-11e7-84c6-50b3cfa40990.png)

Второе изображение:
![image](https://user-images.githubusercontent.com/27721442/32278130-bc672ff2-bf25-11e7-8011-9a07036a866f.png)

Оригинальные изображения:
[HelpDeskPics.zip](https://github.com/AtlantisUnited/plumsail/files/1434344/HelpDeskPics.zip)

**Comment by alexsimkovich** [comment]
@jusper-dk ready

**Comment by jusper-dk** [comment]
Круто, но по-прежнему ничего не происходит при наведении на тот или иной пункт. Еще раз, при наведении на к-либо пункт, он должен подсвечиваться. До наведения, как сейчас, автоматическая смена пунктов с интервалом.
