### ISSUE TITLE
Become a partner

### ISSUE THREAD

**Issue by TorinAsakura** [AtlantisUnited/plumsail#8]
[Изменить расположение сей кнопки](http://cyberthrone.org/partners-and-resellers/), говорят не видно

**Comment by jusper-dk** [comment]
Из доки:
Кнопку Become a partner перенести под заголовок trusted partners и разместить по центру, а то сейчас она незаметна. 

Откуда вопрос рядом с Resellers? URL страницы должен быть /partners-and-resellers/ 

Locatech - текст вылез за рамку.
