### ISSUE TITLE
Переверстать страницы загрузки продуктовой линейки

### ISSUE THREAD

**Issue by TorinAsakura** [AtlantisUnited/plumsail#9]
- Страницы скачивания продуктов сделать в стиле родительских страниц
  - [Reference](http://cybethrone.org/sharepoint-helpdesk/download/)    
- Активные элементы в фокусе должны быть выполнены таким цветом rgb(238, 132, 0);
  - кнопка
  - активные поля ввода
  - выбранные версии
  - заголовок должны

**Comment by TorinAsakura** [comment]
Я вообще хз о чём вы, я [подобные страницы](http://test.asight.ru/sharepoint-dashboard-designer/download-links/  ) не видел, так как на них нет ссылок по ресурсу (по крайней мере я не нашёл) поэтому я делал сразу как мне показалось правильным http://cybethrone.org/sharepoint-helpdesk/download/ - или чот не так?(

**Comment by jusper-dk** [comment]
Во-первых, сравни урлы (последняя часть):
https://plumsail.com/sharepoint-helpdesk/download/
http://cyberthrone.org/sharepoint-helpdesk/helpdesk-download/

Ты мне говорил, чего тут париться, я переношу friendly links как есть, почему они должны поменяться и вся такая фигня.

Во-вторых, нужно чтобы все, что лежит внутри продукта, было в цветовой гамме продукта. Обрати внимание на лэндинги всех продуктов. У всех свой primary color и цвет ссылки. Тот же стиль должен наследоваться во всех дочерних страницах.

**Comment by alexsimkovich** [comment]
@jusper-dk @TorinAsakura и здесь распишите плз

**Comment by jusper-dk** [comment]
Страница скачивания продукта
https://cyberthrone.org/workflow-action-pack/download/

Должна быть в цветах продукта: активные поля ввода, кнопки, заголовок. То же для других продуктов

**Comment by alexsimkovich** [comment]
@jusper-dk Ready to check
